/**
 * Types of Standard Operating Procedures
 */
export enum SOPType {
  CLINICAL = 'CLINICAL',
  ADMINISTRATIVE = 'ADMINISTRATIVE',
  COMPLIANCE = 'COMPLIANCE',
  HR = 'HR',
  QUALITY = 'QUALITY',
  EMERGENCY = 'EMERGENCY',
  TECHNOLOGY = 'TECHNOLOGY',
  FINANCIAL = 'FINANCIAL',
  MARKETING = 'MARKETING'
} 